env_list = ["3.13", "3.12", "3.11", "3.10", "3.9", "lint"]

[env_run_base]
description = "Test suite"
deps = [
    "pytest>=8"
]
commands = [["pytest", "--basetemp={env_tmp_dir}", { replace = "posargs", default = ["tests"], extend = true }]]

[env.lint]
description = "Run linters"
skip_install = true
deps = ["ruff"]
commands = [["ruff", "check", { replace = "posargs", default = ".", extend = true}]]
